config/routes.rb
Oskar::Application.routes.draw do
  root 'home#index'

  match 'contact' => 'home#create', :as => 'contact', :via => :post
  resources :galleries
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :body

  validates :name, :email, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  protected

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "foo" && password == "bar"
    end
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:destroy]
  before_filter :authenticate

  def index
    @galleries = Gallery.all
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(gallery_params)

    if @gallery.save
      redirect_to galleries_path
    else
      render action: 'new'
    end
  end

  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @message = Message.new
    @galleries = Gallery.all
  end

  def create
    @message = Message.new(params[:message])
    @galleries = Gallery.all
    
    NotificationsMailer.new_message(@message).deliver if @message.valid?
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/galleries/_form.html.haml
= simple_form_for(@gallery, :html => {:multipart => true}) do |f|
  = f.error_notification
  .span11
    .form-inputs
      = f.input :image, as: :file

    = f.button :submit, "Загрузить"

app/views/galleries/index.html.haml
.span12
  .page-header
    .pull-right
      = link_to 'Загрузить фото', new_gallery_path, class: 'btn btn-success'
    %h1 Фото

  - if @galleries.present?
    %table.table.table-stripped.table-hover
      %thead
        %tr
          %th Фото
      %tbody
      - @galleries.each do |gallery|
        %tr
          %td= image_tag gallery.image_url(:thumb).to_s
          %td= link_to 'Destroy', gallery, :method => :delete, :data => { :confirm => 'Are you sure?' },                      :class => 'btn btn-danger btn-small'
  - else
    .alert.alert-warning Нет результатов

app/views/galleries/new.html.haml
%h1 Загрузить новую фотографию.

= render 'form'

app/views/home/index.html.haml
/ start: header
.header-wrap
  %header.clearfix

/ end: header

/ start: welcome
.welcome-wrap
  .container
    %h2 Добро пожаловать на наш сайт.
/ end: welcome

/ start: about us
.about-us
  %a#about
  .container
    .page-header
      %h1 О нас
    %h2.slogan
      %p
        Мы очень рады приветствовать Вас на сайте нашего агентства! Наверное, у Вас скоро свадьба? Вы в растерянности и не знаете с чего начать?
      %p
        Свадебное агентство «Oskar» - Это Ваш партнер и помощник в организации свадебного торжества!
      %p
        Наша цель - превратить Ваши мечты и желания в реальность!
      %p
        Основная задача - сделать Вашу свадьбу, ярким и незабываемым днем! Подарить Вам спокойствие и отличное настроение на празднике!
    .row-fluid
      .span4
      .span4.image-span
        .image-inner
          = image_tag('image4.jpg', class: "img-circle")
      .span4
/ end: about us
.gallery-pre
  .container
    .page-header
      %a#gallery
      %h1 Галлерея
    %h2.slogan Наша свадебная галлерея.

.gallery
  .container
    %section#gallery-grid.row.thumbnails.isotope{:style => "position: relative; overflow: hidden;"}
      - @galleries.each do |photo|
        %article.span3.isotope-item
          .thumbnail.hover
            = image_tag(photo.image_url(:thumb).to_s)
            .mask
            .caption
              %span.ico_block
                %a.ico_zoom.prettyPhoto{:href => "#{photo.image.url}", :rel => 'prettyPhoto'}
                  %span
    / end: Gallery
/ start: wedding-pre
.wedding-pre
  .container
    .page-header
      %a#wedding
      %h1 Информация
    %h2.slogan 
      %b Мы несем полную ответственность за качество предоставляемых услуг!!! 
/ end: wedding-pre

/ start: wedding
.wedding
  .container
    .row-fluid
      .span6
        %h2 Почему Вы должны выбрать именно нас!
        %ul
          %li Мы дадим Вам 100% гарантию Вашего спокойствия в день свадьбы!
          %br
          %li Мы работаем только с профессионалами!
          %br
          %li Мы организовываем и создаем свадьбы, только исходя из Ваших пожеланий и предпочтений!
          %br
          %li Мы делаем свою работу быстро и качественно!
          %br
          %li Индивидуальный подход к каждой паре!
        %br
        %p{ style: "text-align: left;"}
          Организация свадеб - это для нас, в первую очередь, любимое дело, которым мы живем и, от которого, мы получаем только позитивные эмоции!!! 
      .span6
        %h2 Услуги
        %br
        %b Мы продумаем все до мелочей:
        #list
          %ul
            %li индивидуальный стиль для Вашей свадьбы;
            %br
            %li подбор ресторана, усадьбы;
            %br
            %li фотограф, видеооператор,
            %br
            %li ведущий, артисты;
            %br
            %li выездная регистрация; 
            %br
            %li оформление зала, подбор цветовой гаммы, аксессуары;
            %br
            %li свадебная полиграфия;
            %br
            %li координация свадьбы;
            %br
            %li подбор автомобилей для свадебного кортежа;
            %br
            %li визажист, парикмахер, стилист;
            %br
            %li выбор свадебного торта;
            %br
            %li кейтеринг ;
            %br
            %li оформление фотозоны;
            %br
            %li флористика (свадебный букет, оформление свадьбы живыми цветами) и многое другое!!!
    .row-fluid
      .span8.offset2
        %br
        %h2 Стоимость
        %br
        %p{ style: "text-align: left"}
          * Полная организация свадьбы - для тех пар, которые  решили организовать  свадьбу, с помощь профессиональной команды! В данный пакет входят:
        %br
        %ul.offset1
          %li
            Свадебный организатор, который начинает с Вами работать с момента подписания договора. Это Ваш личный гид в свадебном мире!
          %br
          %li 
            2 свадебных координатора -  БЕСПЛАТНО (работают на свадебной площадке в свадебный день).
        %br
        %p{ style: "text-align: left"}
          Комиссия нашего агентства в данном случае составляет 10% от общей сметы (аренда свадебной площадки и меню, не включаются в смету).
        %br
        %p{ style: "text-align: left"}
          * При заказе двух и более услуг – комиссия так же 10% от общей сумма Вашего заказа.
        %br
        %p{ style: "text-align: left"}
          * Если же Вы решили организовать свадьбу самостоятельно  и воспользоваться только отдельной услугой нашего агентства, то в этом случае, комиссия составит - 400 000 бел. рублей. 
/ end: wedding

/ start: contact
.contact
  .container
    .page-header
      %h1 Контакты
    %a#venue
    %h2.slogan Звоните прямо сейчас! Мы с удовольствием ответим на все Ваши вопросы!
    .row-fluid
      .span4.info
        %h4 Телефон:
        %p
          +375 33 606-37-26
          &nbsp;
          %img.decore-top{alt:"", src: "#{asset_path('mts.gif')}", width: 50}
      .span8.form
        = simple_form_for @message, :url => contact_path do |f|
          %fieldset
            .control-group
              .controls
                = f.input :name, required: true, placeholder: "Your Name", label: false, :input_html => { class: "span12" }
              .controls
                = f.input :email, required: true, placeholder: "Your Email", label: false, :input_html => { class: "span12" }
              .controls
                = f.input :body, as: :text, required: false, placeholder: "Your Message", label: false, :input_html => {:rows => 6, class: "span12", id: "textarea"}
              = f.button :submit, 'Send', class: "btn btn-inverse pull-right"
/ end: contact

app/views/layouts/_navigations.html.haml
/ Navigation Bar
.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar.collapsed{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand{:href => "#{root_url}"}= "Oskar"
      .nav-collapse.pull-right.collapse{:style => "height: 0px;"}
        %ul#nav.nav
          %li
            %a{:href => "#home"} На главную
          %li
            %a{:href => "#about"} О нас
          %li
            %a{:href => "#gallery"} Галлерея
          %li
            %a{:href => "#wedding"} Информация
          %li
            %a{:href => "#venue"} Контакты
      / /.nav-collapse

app/views/layouts/application.html.haml
!!!
%html.csstransforms.no-csstransforms3d.csstransitions
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title Свадебное агентство Oskar
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = airbrake_javascript_notifier
    = csrf_meta_tags
  %body#home{"data-twttr-rendered" => "true"}
    = render 'layouts/navigations'
    = yield